### ISSUE TITLE
shell copy

### ISSUE THREAD

**Issue by mbocek** [RickStrahl/highlightjs-badge#3]
Hi,
at first a good job :).
I would like to ask you regarding copy functionality. I'm using it in highlighting shell scripts and usually, there is '$' character at the beginning of code e.g.:
```shell
$ echo "test"
```
Is there a way to simply remove it from the copied string?

**Comment by RickStrahl** [comment]
I've added an option function override `.onBeforeTextCopied()` which you can implement to modify the text before it goes into the clipboard buffer.

The base lib won't fix up what's in the actual code block but now you can do it on your own.
